site_name: AI Agent Toolbox
extra:
  cname: toolbox.255labs.xyz
repo_url: https://github.com/255BITS/ai-agent-toolbox
docs_dir: docs
site_dir: site

theme:
  name: material
  
  # Set dark mode as default
  palette:
    scheme: slate
    primary: indigo
    accent: indigo
  
  # Navigation settings
  features:
    - navigation.sections        # Sections are collapsible
    - navigation.expand         # Expand all sections by default
    - navigation.indexes        # Section index pages
    - navigation.top           # Back to top button
    - search.suggest          # Search suggestions
    - search.highlight       # Search highlighting
    - content.code.copy     # Copy button on code blocks
    - content.code.annotate # Code annotations
  
  # Icon settings
  icon:
    repo: fontawesome/brands/github

# Customizing appearance further
extra_css:
  - stylesheets/extra.css   # You can create this for custom tweaks

# Make sure code blocks look good in dark mode
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

nav:
  - Home: index.md
  - Getting Started:
    - getting-started/installation.md
    - getting-started/quickstart.md
  - API Reference:
    - api-reference/core-concepts.md
    - api-reference/toolbox.md
    - api-reference/parsers.md
    - api-reference/tool-response.md
    - api-reference/tool-use.md
    - api-reference/formatters.md
